export const countries = [
  {
    name: "Afghanistan",
    cities: [
      "Kabul",
      "Kandahar",
      "Herat",
      "Farah",
      "Mazar-e Sharif",
      "Lashkar Gah",
      "Kunduz",
      "Taluqan",
      "Jalalabad",
      "Shibirghan",
      "Zaranj",
      "Khost",
      "Maimana",
      "Mehtar Lam",
      "Ghazni",
      "Paghman",
      "Pul-e Khumri",
      "Bamyan",
      "Charikar",
      "Tarin Kot",
      "Gardez",
      "Faizabad",
      "Qala-e Naw",
      "Sar-e Pol",
      "Mahmud-e Raqi",
      "Qalat",
      "Asadabad",
      "Maidan Shahr",
      "Bazarak",
      "Pul-e Alam",
      "Fayroz Koh",
      "Khanabad",
      "Andkhoy",
      "Baghlan",
      "Balkh",
      "Bamyan",
      "Chaghcharan",
      "Chaharikar",
      "Gardez",
      "Ghazni",
      "Herat",
      "Jalalabad",
      "Kandahar",
      "Kunduz",
      "Lashkar Gah",
      "Maimana",
      "Mazar-e Sharif",
      "Pul-e Khumri",
      "Sheberghan",
      "Taloqan",
      "Zaranj",
    ],
  },
  {
    name: "Albania",
    cities: [
      "Tirana",
      "Durrës",
      "Vlorë",
      "Kamëz",
      "Fier",
      "Shkodër",
      "Elbasan",
      "Korçë",
      "Sarandë",
      "Berat",
      "Lushnjë",
      "Kavajë",
      "Gjirokastër",
      "Pogradec",
      "Fushë-Krujë",
      "Laç",
      "Kukës",
      "Sukth",
      "Buçimas",
      "Lezhë",
      "Patos",
      "Peshkopi",
      "Librazhd-Qendër",
      "Kuçovë",
      "Krujë",
      "Burrel",
      "Perondi",
      "Libonik",
      "Rrëshen",
      "Belsh",
      "Divjakë",
      "Gramsh",
      "Mamurras",
      "Bulqizë",
      "Vau i Dejës",
      "Shëngjin",
      "Ballsh",
      "Shijak",
      "Bilisht",
      "Rrogozhinë",
      "Librazhd",
      "Cërrik",
      "Roskovec",
      "Manzë",
      "Peqin",
      "Krumë",
      "Përmet",
      "Përrenjas-Fshat",
      "Prrenjas",
      "Delvinë",
      "Orikum",
      "Bajram Curri",
      "Vorë",
      "Këlcyrë",
      "Ura Vajgurore",
      "Himarë",
      "Rubik",
      "Tepelenë",
      "Poliçan",
      "Çorovodë",
      "Ersekë",
      "Maliq",
      "Koplik",
      "Pukë",
      "Lazarat",
      "Memaliaj",
      "Velçan",
      "Banaj",
      "Fushë-Arrëz",
      "Krrabë",
      "Selenicë",
      "Voskopojë",
      "Bitinckë",
      "Drenovë",
      "Libohovë",
      "Reps",
      "Gjinkar",
      "Krastë",
      "Leskovik",
      "Kurbnesh",
      "Konispol",
      "Finiq",
      "Ulëz",
      "Boboshticë",
      "Sinaballaj",
      "Liqenas",
      "Aliaj",
      "Burgajet",
      "Plasë",
      "Rapshë",
      "Vukpalaj-Bajzë",
      "Guri i Bardhë",
      "Dobër",
      "Kastrat",
      "Bogiç-Palvar",
      "Stërbeq",
      "Shtanë",
      "Vernicë",
      "Goricë e Madhe",
      "Dardhë",
      "Vuno",
      "Lajthizë",
      "Gjinovec",
      "Vërnik",
      "Klenjë",
      "Rripë",
    ],
  },
  {
    name: "Algeria",
    cities: [
      "Algiers",
      "Constantine",
      "Batna",
      "Sétif",
      "Djelfa",
      "Annaba",
      "Sidi Aïssa",
      "Sidi Bel Abbès",
      "Biskra",
      "Tébessa",
      "Ouargla",
      "El Khroub",
      "Tiaret",
      "Bejaïa",
      "Tlemcen",
      "Bir el Djir",
      "Bordj Bou Arreridj",
      "Béchar",
      "Blida",
      "Skikda",
      "Souk Ahras",
      "Chlef",
      "El Eulma",
      "Bordj el Kiffan",
      "Mostaganem",
      "Touggourt",
      "Médéa",
      "Tizi Ouzou",
      "El Oued",
      "Laghouat",
      "M’Sila",
      "Jijel",
      "Relizane",
      "Saïda",
      "Baraki",
      "Guelma",
      "Ghardaïa",
      "Aïn Beïda",
      "Maghnia",
      "Bou Saâda",
      "Bou Saada",
      "Mascara",
      "Khenchela",
      "Barika",
      "Messaad",
      "Aflou",
      "Aïn Oussera",
      "Oran",
      "Es Senia",
      "Bab Ezzouar",
      "Tamanrasset",
      "Arzew",
      "Aïn M’Lila",
      "El Bayadh",
      "Mohammadia",
      "Khemis Miliana",
      "Hamma Bouziane",
      "Dar el Beïda",
      "Oum el Bouaghi",
      "Taher",
      "Birkhadem",
      "Khemis el Khechna",
      "Aïn Temouchent",
      "Tissemsilt",
      "Sig",
      "Mila",
      "Bouira",
      "Adrar",
      "Ksar el Boukhari",
      "Reghaïa",
      "Aïn Defla",
      "Bordj Menaïel",
      "Oued Rhiou",
      "Assi Bou Nif",
      "Ouled Djellal",
      "Tighenif",
      "Rouiba",
      "Kolea",
      "Baba Hassen",
      "Lakhdaria",
      "Sidi ech Chahmi",
      "El Attaf",
      "Boufarik",
      "Boudouaou",
      "Oulad Yaïch",
      "Ksar Chellala",
      "Akbou",
      "Zeralda",
      "’Aïn Merane",
      "’Aïn el Turk",
      "Saoula",
      "El Meghaïer",
      "Oued Sly",
      "Douera",
      "Ouled Moussa",
      "Tindouf",
      "Miliana",
      "Beni Saf",
      "El Affroun",
      "Oued Fodda",
      "Boumerdes",
      "Meftah",
      "Sidi Moussa",
      "El Golea",
      "Magra",
      "Staoueli",
      "Draa el Mizan",
      "Emîr Abdelkader",
      "Bougara",
      "Souma",
      "Ouled Beni Messous",
      "Collo",
      "Tebesbest",
      "Aïn Taya",
      "Beni Tamou",
      "Ghazaouet",
      "Didouche Mourad",
      "El Arrouch",
      "Timimoun",
      "Aïn el Bya",
      "I-n-Salah",
      "Bougaa",
      "Draa Ben Khedda",
      "Boghni",
      "Birtouta",
      "Chabet el Ameur",
      "Tizi Gheniff",
      "L’Arbaa Naït Irathen",
      "Ouled Haddaj",
      "Tazmalt",
      "Mouzaïa",
      "Sidi Lakhdar",
      "Isser",
      "Bordj el Bahri",
      "Ouled Fayet",
      "Ouled Slama Tahta",
      "El Abadia",
      "Zemmouri",
      "Kaous",
      "El Tarf",
      "Tipasa",
      "Beni Amrane",
      "Illizi",
      "Bordj Mokhtar",
      "Naama",
      "Djanet",
      "Beni Abbès",
      "In Guezzam",
    ],
  },
  {
    name: "Andorra",
    cities: [
      "Andorra la Vella",
      "Escaldes-Engordany",
      "Encamp",
      "La Massana",
      "Sant Julià de Lòria",
      "Canillo",
      "Ordino",
      "Santa Coloma",
      "Pas de la Casa",
      "Arinsal",
      "El Tarter",
      "Vila",
      "Les Bons",
      "Soldeu",
      "Sispony",
      "La Cortinada",
      "Aixirivall",
      "Anyós",
      "Escàs",
      "Erts",
      "Ransol",
      "Sornàs",
      "Aubinyà",
      "Arans",
      "Pal",
      "Llorts",
      "Juberri",
      "El Serrat",
      "La Comella",
      "Engordany",
      "Els Vilars",
      "La Plana",
      "Ràmio",
      "Engolasters",
      "El Tremat",
      "Puiol del Piu",
      "El Pui",
      "L’Aldosa",
      "Mas de Ribafeta",
      "Xixerella",
    ],
  },
  {
    name: "Angola",
    cities: [
      "Luanda",
      "Cacuaco",
      "Cazenga",
      "Lubango",
      "Cabinda",
      "Huambo",
      "Malanje",
      "Benguela",
      "Belas",
      "Talatona",
      "Lobito",
      "Saurimo",
      "Cubal",
      "Luena",
      "Cuito",
      "Uíge",
      "Menongue",
      "Vila Teixeira da Silva",
      "Sumbe",
      "Gabela",
      "Ndulo",
      "Moçâmedes",
      "Ganda",
      "Uacu Cungo",
      "Mbanza Kongo",
      "Dundo",
      "Ndalatando",
      "Ondjiva",
      "Caxito",
    ],
  },
  {
    name: "Antigua and Barbuda",
    cities: [
      "Saint John's",
      "All Saints",
      "Bolans",
      "Liberta",
      "Piggotts",
      "Swetes",
      "Jennings",
      "Clare Hall",
      "Parham",
      "Willikies",
      "New Winthorpes",
      "Codrington",
      "Old Road",
      "Potters Village",
      "Bendals",
      "Cedar Grove",
      "Freemans",
      "Tomlinson",
      "Buckleys",
      "Sea View Farm",
      "Crosbies",
      "Urlings",
      "Branns Hamlet",
      "Belmont",
      "Falmouth",
      "Cedar Valley Mill",
      "Freetown",
      "Pares",
      "English Harbour Town",
      "Golden Grove",
      "Carlisle",
      "Saint Johnston Village",
      "Vernons",
      "Bethesda",
      "Seatons",
      "John Hughes",
      "Glanvilles",
      "Emanuel",
      "Ebenezer",
      "Five Islands Village",
      "Yepton",
      "Cobbs Cross",
      "Sutherlands Development",
      "Grays Hill",
      "Hattons",
      "Weatherills",
      "Royals",
      "Woods",
      "Boon House",
      "Soldier",
      "Bellevue Heights",
      "Friars Hill",
      "Olivers",
      "Belvedere",
      "Paradise View",
      "Side Hill",
      "Aberdeen",
      "Black Rock",
      "Martin Hill",
      "Sutherland",
      "Saint Clare",
      "Potters Buff",
      "Herberts",
      "Cassada Gardens",
      "Renfrew",
      "Creekside",
      "Saint Lukes",
      "Follys",
      "Bellevue",
      "Lightfoots",
      "Paynters",
      "Osbourn",
      "The Grove",
      "Barnes Hill",
      "Fitches Creek",
      "Gunthorpes",
      "North Sound",
      "Sawcolts",
      "Weirs",
      "Seaforths",
      "Matthews",
      "Red Hill",
      "Table Hill Gordon",
      "Bats Cave",
      "Guinea Bush",
      "Brooks",
      "Willis Freemans",
      "Richmond",
      "Christian Hill",
      "The Ordnance Land",
      "Pattersons",
      "Mount William",
      "Pattersons Dwelling House",
      "Saint Helena",
      "Green Hill",
      "Tyrells",
    ],
  },
  {
    name: "Argentina",
    cities: [
      "Buenos Aires",
      "Córdoba",
      "Rosario",
      "Santiago del Estero",
      "Comodoro Rivadavia",
      "Mar del Plata",
      "San Miguel de Tucumán",
      "Salta",
      "San Juan",
      "Lanús",
      "Santa Fe",
      "Corrientes",
      "San Salvador de Jujuy",
      "Bahía Blanca",
      "Pilar",
      "Resistencia",
      "Posadas",
      "Quilmes",
      "Paraná",
      "Merlo",
      "González Catán",
      "Formosa",
      "Neuquén",
      "Banfield",
      "José C. Paz",
      "San Rafael",
      "Río Cuarto",
      "La Plata",
      "Godoy Cruz",
      "Isidro Casanova",
      "Las Heras",
      "La Rioja",
      "Berazategui",
      "San Luis",
      "San Fernando",
      "General Roca",
      "José María Ezeiza",
      "San Nicolás de los Arroyos",
      "Catamarca",
      "San Miguel",
      "Concordia",
      "Rafael Castillo",
      "Florencio Varela",
      "San Justo",
      "Ituzaingó",
      "Temperley",
      "Ramos Mejía",
      "Puerto Madryn",
      "Mendoza",
      "San Carlos de Bariloche",
      "Lomas de Zamora",
      "Villa Mercedes",
      "Bernal",
      "Esteban Echeverría",
      "Gualeguaychú",
      "Castelar",
      "Villa Krause",
      "Luján",
      "Maipú",
      "La Banda",
      "Pergamino",
      "Santa Rosa",
      "Concepción del Uruguay",
      "Libertad",
      "Morón",
      "Burzaco",
      "Zárate",
      "Río Grande",
      "Trelew",
      "Río Gallegos",
      "Caseros",
      "Villa Luzuriaga",
      "Ciudad General Belgrano",
      "Rafaela",
      "San Francisco Solano",
      "Necochea",
      "Presidencia Roque Sáenz Peña",
      "Olavarría",
      "Villa María",
      "Berisso",
      "Chimbas",
      "Campana",
      "Junín",
      "General Rodríguez",
      "Grand Bourg",
      "Monte Chingolo",
      "Rivadavia",
      "Puerto Iguazú",
      "Remedios de Escalada",
      "Gobernador Gálvez",
      "Ezpeleta",
      "San Martín",
      "Villa Celina",
      "San Ramón de la Nueva Orán",
      "San Pedro",
      "Villa Carlos Paz",
      "Reconquista",
      "Ciudadela",
      "Luján de Cuyo",
      "Goya",
      "Bella Vista",
      "Lomas del Mirador",
      "Oberá",
      "Wilde",
      "Martínez",
      "Santo Tomé",
      "Don Torcuato",
      "Gerli",
      "Pirané",
      "Mercedes",
      "Banda del Río Salí",
      "Tartagal",
      "Villa Domínico",
      "San Francisco",
      "Viedma",
      "Los Polvorines",
      "Sarandí",
      "Hurlingham",
      "Garín",
      "El Palomar",
      "Beccar",
      "San Pedro",
      "Punta Alta",
      "Chivilcoy",
      "Glew",
      "General Pico",
      "Cosquín",
      "Eldorado",
      "Tres Arroyos",
      "Ushuaia",
      "Rafael Calzada",
      "Azul",
      "Barranqueras",
      "Belén de Escobar",
      "Ensenada",
      "Mariano Acosta",
      "Clorinda",
      "Guernica",
      "El Talar de Pacheco",
      "Palpalá",
      "Yerba Buena",
      "Concepción",
      "Villaguay",
      "Tunuyán",
      "Florida",
      "Alta Gracia",
      "La Reja",
      "San Lorenzo",
      "Longchamps",
      "Catriel",
      "Villa Constitución",
      "General Martín Miguel de Güemes",
      "Libertador General San Martín",
      "Río Tercero",
      "San Lorenzo",
      "Trenque Lauquen",
      "Chajarí",
      "Balcarce",
      "San Vicente",
      "San Isidro",
      "General Pacheco",
      "Paso de los Libres",
      "Dock Sur",
      "Gualeguay",
      "Coronel Suárez",
      "Esperanza",
      "Tolosa",
      "Llavallol",
      "Villa Ángela",
      "Tortuguitas",
      "Claypole",
      "Villa Alsina",
      "José Mármol",
      "Apóstoles",
      "Pinamar",
      "Tafí Viejo",
      "Virreyes",
      "Marcos Paz",
      "Ingeniero Pablo Nogués",
      "Chacabuco",
      "Aristóbulo del Valle",
      "San Antonio de Padua",
      "Haedo",
      "Granadero Baigorria",
      "Nueve de Julio",
      "Munro",
      "Cutral-Có",
      "Villa Adelina",
      "Villa Ballester",
      "Casilda",
      "Centenario",
      "Bell Ville",
      "Chilecito",
      "Chascomús",
      "Bragado",
      "City Bell",
      "Plottier",
      "La Calera",
      "Termas de Río Hondo",
      "Aguilares",
      "Zapala",
      "Quitilipi",
      "Fontana",
      "Cañuelas",
      "Avellaneda",
      "General José de San Martín",
      "Jesús María",
      "Pehuajó",
      "Lobos",
      "Pichanal",
      "Cruz del Eje",
      "Gobernador Virasora",
      "Miramar",
      "Villa Regina",
      "Villa Dolores",
      "Villa Gesell",
      "Capitán Bermúdez",
      "Cañada de Gómez",
      "Garupá",
      "Bella Vista",
      "Baradero",
      "General San Martín",
      "Adrogue",
      "Lincoln",
      "San Martín de los Andes",
      "Marcos Juárez",
      "Arrecifes",
      "Las Flores",
      "Charata",
      "Pérez",
      "Muñiz",
      "Dolores",
      "Firmat",
      "Jardín América",
      "Mar de Ajó",
      "Leandro N. Alem",
      "Candelaria",
      "Tres Isletas",
      "Rawson",
      "La Paz",
      "Monte Caseros",
      "Veinticinco de Mayo",
      "Santo Tomé",
      "Monteros",
      "Colón",
      "San Andrés de Giles",
      "Las Breñas",
      "Famaillá",
      "Nogoyá",
      "San Martín",
      "Machagai",
      "San Justo",
      "Rosario de Lerma",
      "San Antonio de Areco",
      "Carlos Casares",
      "San Isidro de Lules",
      "Brandsen",
      "Diamante",
      "Saladas",
      "Coronda",
      "General Juan Madariaga",
      "Cerrillos",
      "Puerto Rico",
      "La Quiaca",
      "Federación",
      "General Pinedo",
      "Villa del Rosario",
      "San Luis del Palmar",
      "Bella Vista",
      "Carmen de Areco",
      "Las Rosas",
      "General Belgrano",
      "General Viamonte",
      "Empedrado",
      "Rosario del Tala",
      "General Las Heras",
      "San Salvador",
      "Junín de los Andes",
      "La Carlota",
      "Villa Berthet",
      "Cafayate",
      "Oliva",
      "Santa Lucía",
      "Navarro",
      "Ramallo",
      "Capitán Sarmiento",
      "San Bernardo",
      "Roque Pérez",
      "Bernardo de Irigoyen",
      "San Roque",
      "Santa Rosa de Río Primero",
      "Campo Largo",
      "Corzuela",
      "Ranchos",
      "La Leonesa",
      "Puerto Tirol",
      "Magdalena",
      "Capilla del Señor",
      "Mburucuyá",
      "Villa Aberastain",
      "Simoca",
      "Alberti",
      "Villa Media Agua",
      "Itatí",
      "San Ignacio",
      "Realicó",
      "Villa del Totoral",
      "Mar del Tuyú",
      "Villa Cura Brochero",
      "Coronel Vidal",
      "Tilcara",
      "Junín",
      "Margarita Belén",
      "Sastre",
      "Macachín",
      "Colonia Elisa",
      "San Isidro",
      "San Cosme",
      "General Arenales",
      "Makallé",
      "San Agustín",
      "Melincué",
      "San José",
      "Bañado de Ovanta",
      "Arraga",
      "Alba Posse",
      "Tandil",
      "Olivos",
      "Tigre",
      "Santa Lucía",
      "El Carmen",
      "Dolores",
      "Monte Hermoso",
      "Villa Alberdi",
      "Campo Grande",
      "Puerto Esperanza",
      "Santa Ana",
      "Fernández",
      "San Javier",
      "El Soberbio",
      "Chicoana",
      "Montecarlo",
      "Salto",
      "La Cocha",
      "San Antonio",
      "Villa San Isidro",
      "Santa Rosa del Conlara",
      "Tupungato",
      "San Miguel del Monte",
      "Concepción de la Sierra",
      "Saladillo",
      "Suipacha",
      "Rojas",
      "Burruyacú",
      "Vedia",
      "Salliqueló",
      "La Caldera",
      "Concarán",
      "Graneros",
      "Metán",
      "Esquina",
      "San Carlos de Bolívar",
      "Aimogasta",
    ],
  },
  {
    name: "Armenia",
    cities: [
      "Yerevan",
      "Gyumri",
      "Vanadzor",
      "Ejmiatsin",
      "Hrazdan",
      "Abovyan",
      "Kapan",
      "Armavir",
      "Charentsavan",
      "Stepanavan",
      "Sevan",
      "Ashtarak",
      "Masis",
      "Artashat",
      "Ararat",
      "Gavarr",
      "Goris",
      "Ijevan",
      "Artik",
      "Dilijan",
      "Spitak",
      "Sisian",
      "Vedi",
      "Alaverdi",
      "Vardenis",
      "Martuni",
      "Yeghvard",
      "Vardenik",
      "Metsamor",
      "Berd",
      "Byureghavan",
      "Nor Hachn",
      "Tashir",
      "Nerk’in Getashen",
      "Ayntap",
      "Sarukhan",
      "Yeghegnadzor",
      "Nor Kharberd",
      "Kajaran",
      "Jrvezh",
      "Noratus",
      "Aparan",
      "Zolakar",
      "Arrinj",
      "Chambarak",
      "Parakar",
      "Zovuni",
      "Yeranos",
      "Lichk",
      "Maralik",
      "Nor Geghi",
      "Noyemberyan",
      "Sardarapat",
      "Proshyan",
      "Tsovinar",
      "Aragatsavan",
      "Verin Getashen",
      "Mrgashat",
      "Talin",
      "Lchashen",
      "Nalbandyan",
      "Azatan",
      "Vosketap",
      "Dzoragyugh",
      "Meghri",
      "Metsavan",
      "Mkhchyan",
      "Karakert",
      "Malishka",
      "Akunk",
      "Koghb",
      "Byurakan",
      "Verin Artashat",
      "Gugark",
      "Vaghashen",
      "Achajur",
      "Arshaluys",
      "Astghadzor",
      "Voskevaz",
      "Jermuk",
      "Odzun",
      "Myasnikyan",
      "Dalarik",
      "Tsovagyugh",
      "Geghashen",
      "Aygavan",
      "Avshar",
      "Gandzak",
      "Agarak",
      "Haghartsin",
      "Karbi",
      "Gay",
      "Voskehat",
      "Margahovit",
      "Balahovit",
      "Gandzakar",
      "Aramus",
      "Arteni",
      "Pemzashen",
      "Hovtashat",
      "Panik",
      "Mets Masrik",
      "Taperakan",
      "Bambakashat",
      "Aragats",
      "Jrashen",
      "Aygehovit",
      "P’ok’r Vedi",
      "K’anak’erravan",
      "P’ok’r Mant’ash",
      "Norashen",
      "Aygezard",
      "Armavir",
      "Berdavan",
      "Jrarrat",
      "Sarrnaghbyur",
      "Janfida",
      "Aragats",
      "Lerrnanist",
      "Marmarashen",
      "Vardadzor",
      "Artsvaberd",
      "Aghavnatun",
      "Baghramyan",
      "Artsvanist",
      "Ddmashen",
      "Kaghtsrashen",
      "Dvin",
      "Geghanist",
      "Vostan",
      "Norakert",
      "Darakert",
      "Tsovasar",
      "Lusarrat",
      "Tsakkar",
      "Shinuhayr",
      "Musalerr",
      "Haytagh",
      "Dalar",
      "Urtsadzor",
      "Aknalich",
      "Geghakert",
      "Shnogh",
      "Mets Mant’ash",
      "Bjni",
      "Arevashogh",
      "Azatamut",
      "Khoronk",
      "Arratashen",
      "Vzhan",
      "Argel",
      "Sasunik",
      "Arevshat",
      "Tegh",
      "Mastara",
      "Arevik",
      "Ayrum",
      "Aygestan",
      "Arzakan",
      "Armash",
      "Tairov",
      "Vanashen",
      "Goravan",
      "Karchaghbyur",
      "Hatsik",
      "Zartonk",
      "Tsovak",
      "Ohanavan",
      "Meghradzor",
      "Argavand",
      "Nor Kyank’",
      "Arzni",
      "Verishen",
      "Aralez",
      "Solak",
      "Lukashin",
      "Yeghegnut",
      "Aygeshat",
      "Kaghsi",
      "Sevsar",
      "Mayakovski",
      "Norabats",
      "Kuchak",
      "Getashen",
      "Dsegh",
      "Sarchapet",
      "Gladzor",
      "Dzoraghbyur",
      "Getahovit",
      "Hayanist",
      "Kurtan",
      "Lanjaghbyur",
      "Akhtala",
      "Mrgavet",
      "Kamaris",
      "Anushavan",
      "Khndzoresk",
      "Noramarg",
      "Akori",
      "Pshatavan",
      "Aygedzor",
      "Marmashen",
      "Horrom",
      "Ghukasavan",
      "Koti",
      "Kasakh",
      "Getap",
      "Dashtavan",
      "Parpi",
      "Brrnakot’",
      "Argavand",
      "Shahumyan",
      "Goght",
      "Tsovazard",
      "Varser",
      "Taronik",
      "Aghavnadzor",
      "Sayat’-Nova",
      "Getazat",
      "Akunk",
      "Gyulagarak",
      "Burastan",
      "Voskehask",
      "Apaga",
      "Griboyedov",
      "Sisavan",
      "Mets Parni",
      "Hnaberd",
      "Yeraskhahun",
      "Verin Dvin",
      "Shirakamut",
      "Arevshat",
      "Aygeshat",
      "Ptghunk",
      "Arrap’i",
      "Zorak",
      "Areni",
      "Khasht’arrak",
      "Mosesgegh",
      "Masis",
      "Norapat",
      "Shatin",
      "Tandzut",
      "Nshavan",
      "Geghamavan",
      "Artimet",
      "Nor Kyank’",
      "Lerrnagog",
      "Zovaber",
      "Mayisyan",
      "Norashen",
      "Darpas",
      "Spandaryan",
      "Gegharkunik",
      "Araks",
      "Shahumyan",
      "Shenavan",
      "Noyakert",
      "Verin Karmiraghbyur",
      "Nor Armavir",
      "Nor Yerznka",
      "Merdzavan",
      "Ushi",
      "Baghramyan",
      "Aghdzk",
      "Tsaghkahovit",
      "Jrashen",
      "Mrgavan",
      "Jrarbi",
      "Tumanyan",
      "Ptghni",
      "Angeghakot",
      "Khanjyan",
      "Getapnya",
      "Alashkert",
      "Aknashen",
      "Berkanush",
      "Arevik",
      "Agarak",
      "Chochkan",
      "Kotayk",
      "Buzhakan",
      "Katnajur",
      "Harrich",
      "Amasia",
      "Arevashat",
      "Haykavan",
      "Gargarr",
      "Lenughi",
      "Parravak’ar",
      "Vahramaberd",
      "Tavush",
      "Lusakunk",
      "Shatjrek",
      "Meghrashen",
      "Aygek",
      "Shenavan",
      "Yeghegnavan",
      "Nerk’in Bazmaberd",
      "Rranch’par",
      "Lerrnakert",
      "Abovyan",
      "Rrind",
      "Basen",
      "Dimitrov",
      "Lanjazat",
      "Zarrit’ap’",
      "Karahunj",
      "Araks",
      "Lerrnavan",
      "Arazap",
      "Saramej",
      "Teghut",
      "Kamo",
      "Doghs",
      "Zarr",
      "Bardzrashen",
      "Nizami",
      "Fioletovo",
      "Saratak",
      "Yerazgavors",
      "Dzithankov",
      "Lerrnhovit",
      "Agarakadzor",
      "Aygepat",
      "Tsaghkalanj",
      "Katnaghbyur",
      "Nor Kesaria",
      "Margara",
      "Voskevan",
      "Vardablur",
      "Akhurik",
      "Zoravan",
      "Aghavnadzor",
      "Geghanist",
      "Sarigyugh",
      "Nor Artagers",
      "Artashar",
      "Darbnik",
      "Sarahart",
      "Kaputan",
      "Yelpin",
      "Sis",
      "Norashen",
      "Tsaghkadzor",
      "Shaki",
      "Tsaghkaber",
      "Byuravan",
      "Mrgashen",
      "Saralanj",
      "Metsamor",
      "Haghtanak",
      "Jrarrat",
      "Agarak",
      "Shirak",
      "Arpi",
      "Tsaghkunk",
      "Geghamasar",
      "Vahan",
      "Archis",
      "Bazum",
      "Haykashen",
      "Gosh",
      "Vernashen",
      "Madina",
      "Haykavan",
      "Vanand",
      "Mrganush",
      "Nor Kyurin",
      "Korrnidzor",
      "Jrahovit",
      "Vahagni",
      "Navur",
      "Gogaran",
      "Khachaghbyur",
      "Tsiatsan",
      "Gharibjanyan",
      "Norashen",
      "Hovtamej",
      "Zangakatun",
      "Nahapetavan",
      "Hartagyugh",
      "Hovtashen",
      "Ashnak",
      "Kanachut",
      "Deghdzut",
      "Arevabuyr",
      "Urrut",
      "Aragatsotn",
      "Norakert",
      "Aruch",
      "Lusagyugh",
      "Narek",
      "Melikgyugh",
      "Khnatsakh",
      "Aragyugh",
      "Keti",
      "Arjut",
      "Azatavan",
      "Artabuynk",
      "Lchap",
      "Kakavadzor",
      "Shenik",
      "Voskehat",
      "Shaghat",
      "Mrgastan",
      "Dzorakap",
      "Khot",
      "Ttujur",
      "Hatsik",
      "Gusanagyugh",
      "Karaberd",
      "Hartavan",
      "Fantan",
      "Lusaghbyur",
      "Geghasar",
      "Shaghap",
      "Lermontovo",
      "Drakhtik",
      "Nerk’in Sasunashen",
      "Nerk’in Karmiraghbyur",
      "Zovk",
      "Tsaghkunk",
      "Choratan",
      "Vardenut",
      "Verin Ptghni",
      "Yeghegnut",
      "Baghanis",
      "Zorakan",
      "Bazmaghbyur",
      "Chinari",
      "Tsaghkavan",
      "Agarakavan",
      "Kat’narrat",
      "Harzhis",
      "Tatev",
      "Hayrenyats",
      "Hushakert",
      "Lanjik",
      "Karrnut",
      "Amasia",
      "Nor Artamet",
      "Mets Sepasar",
      "Voghjaberd",
      "Lejan",
      "Kaps",
      "Ptghavan",
      "Jajurr",
      "Gndevaz",
      "Vardanashen",
      "Isahakyan",
      "Sotk",
      "Tatul",
      "Arevatsag",
      "Debet",
      "Yeghipatrush",
      "Voskepar",
      "Garrni",
      "Getap",
      "Davit’ Bek",
      "Berk’arrat",
      "Syunik",
      "Mughni",
      "Dasht",
      "Berdik",
      "Jrapi",
      "Katnaghbyur",
      "Vazashen",
      "Nor Ughi",
      "Jrashen",
      "Artanish",
      "Lusakert",
      "Getargel",
      "Karaglukh",
      "Byurakn",
      "Geghadir",
      "Hobardzi",
      "Ditak",
      "Azatashen",
      "Araksavan",
      "Beniamin",
      "Dzorashen",
      "Avan",
      "Mikhayelovka",
      "Irind",
      "Lusagyugh",
      "Karmir Gyukh",
      "Vardakar",
      "Herher",
      "Davtashen",
      "Aygabats",
      "Shamlugh",
      "Vardenis",
      "Getamej",
      "Shirakavan",
      "Chiva",
      "Yervandashat",
      "Teghut",
      "Hayravank",
      "Lusadzor",
      "Debetavan",
      "Haghpat",
      "Karenis",
      "Tsaghkashen",
      "Karinj",
      "Yeraskh",
      "Bayandur",
      "Karmrashen",
      "Nor Khach’akap",
      "Apnagyugh",
      "Varagavan",
      "Nor Amanos",
      "P’ok’r Masrik",
      "Artsvanik",
      "Bagaran",
      "Lorut",
      "Hovuni",
      "Arayi",
      "Jil",
      "Shatvan",
      "Hnaberd",
      "Oshakan",
      "Yernjatap",
      "Nor Gyugh",
      "Katnaghbyur",
      "Hatsavan",
      "Karashamb",
      "Akunk",
      "Vaghatin",
      "Artashavan",
      "Ashotavan",
      "Zarinja",
      "Mets Ayrum",
      "Lehvaz",
      "Ginevet",
      "Arpunk",
      "Hovit",
      "Tsoghamarg",
      "Chinchin",
      "Darbas",
      "Tsilkar",
      "Halidzor",
      "Karashen",
      "Pambak",
      "Oghji",
      "Getk",
      "Yenokavan",
      "Lerrnapar",
      "Lusaghbyur",
      "Akhlatyan",
      "Dovegh",
      "Argina",
      "Vosketas",
      "Nurrnus",
      "Rrya T’aza",
      "Amrakits",
      "Berkashat",
      "Sarakap",
      "Jujevan",
      "Akner",
      "Aknaghbyur",
      "Ghazanchi",
      "Martuni",
      "Agagchi",
      "Marts",
      "Torfavan",
      "Hoghmik",
      "Bavra",
      "Dprabak",
      "Aygepar",
      "Dashtakar",
      "Noravan",
      "Tufashen",
      "Nor Art’ik",
      "Lusashogh",
      "Norashen",
      "Sarrnakunk’",
      "Vardashen",
      "Shgharshik",
      "Teghenik",
      "Tsaghkashen",
      "Sipanik",
      "Artavaz",
      "Vardablur",
      "Krasar",
      "Berkaber",
      "Ghursali",
      "Akhuryan",
      "Verin Bazmaberd",
      "Ghazaravan",
      "T’arrat’umb",
      "Charchakis",
      "Kayk",
      "Alagyaz",
      "Aghitu",
      "Hovk’",
      "Lchkadzor",
      "Tsamakasar",
      "Mghart",
      "Karin",
      "Orgov",
      "Shamb",
      "Zuygaghbyur",
      "Lorri Berd",
      "Makenis",
      "Hagvi",
      "Shenavan",
      "Khoznavar",
      "Uyts",
      "Kachachkut",
      "Goghovit",
      "Musayelyan",
      "Aregnadem",
      "Lerrnamerdz",
      "Aghin",
      "Koghes",
      "Aznvadzor",
      "Jraber",
      "Kakhakn",
      "Spandaryan",
      "Getik",
      "Tavshut",
      "Yeghegis",
      "Vanevan",
      "Lor",
      "Lusahovit",
      "Geghard",
      "Bardzruni",
      "Tsapatagh",
      "Armanis",
      "Antarrut",
      "Akhpradzor",
      "Kirants",
      "Khachardzan",
      "Medovka",
      "Ditavan",
      "Urasar",
      "Barekamavan",
      "Areguni",
      "Pambak",
      "Pushkino",
      "Yeghnik",
      "Mets Sariar",
      "Dzoragyugh",
      "Torosgyugh",
      "Sizavet",
      "Tolors",
      "Aniavan",
      "Karadzor",
      "Verin Sasnashen",
      "Khach’p’arr",
      "Saralanj",
      "Meghrashat",
      "Mutsk",
      "Karkop",
      "Partizak",
      "Ayrk",
      "Pyunik",
      "Ferik",
      "Lerrnarot",
      "Antarramut",
      "Dzoraglukh",
      "Geghahovit",
      "Berdkunk",
      "Hovtashen",
      "Ishkhanasar",
      "Neghots",
      "Kaniashir",
      "Itsakar",
      "Kutakan",
      "Deghdzavan",
      "Noravan",
      "Dzoramut",
      "Nerk’in Khndzoresk",
      "Arpeni",
      "Yeghvard",
      "Suser",
      "Svarants",
      "Vorotan",
      "Dzoraget",
      "Antarrashen",
      "Khnkoyan",
      "Bandivan",
      "Shamut",
      "Shenkani",
      "Hatsavan",
      "Shahumyan",
      "GeGhanush",
      "Avazan",
      "Dashtadem",
      "Norabak",
      "Krashen",
      "Petrovka",
      "Horbategh",
      "P’ok’r Sariar",
      "Artsni",
      "Chknagh",
      "Yaghdan",
      "Bovadzor",
      "Avshen",
      "ShikahoGh",
    ],
  },
  {
    name: "Australia",
    cities: [
      "Canberra",
      "Melbourne",
      "Sydney",
      "Brisbane",
      "Perth",
      "Adelaide",
      "Gold Coast",
      "Cranbourne",
      "Central Coast",
      "Wollongong",
      "Ipswich",
      "Hobart",
      "Geelong",
      "Townsville",
      "Newcastle",
      "Cairns",
      "Darwin",
      "Ballarat",
      "Toowoomba",
      "Bendigo",
      "Mandurah",
      "Launceston",
      "Mackay",
      "Hervey Bay",
      "Buderim",
      "Wagga Wagga",
      "Pakenham",
      "Port Macquarie",
      "Caloundra",
      "Frankston",
      "Sunbury",
      "Gladstone",
      "Bathurst",
      "Palmerston",
      "Southport",
      "Dandenong",
      "Warrnambool",
      "Quakers Hill",
      "Mount Gambier",
      "Traralgon",
      "Whyalla",
      "Armidale",
      "Burnie",
      "Griffith",
      "Mount Eliza",
      "Maroochydore",
      "Taree",
      "Banora Point",
      "Lara",
      "Cessnock",
      "Horsham",
      "Murray Bridge",
      "Wallan",
      "Australind",
      "Ormeau",
      "Barwon Heads",
      "Mount Barker",
      "Morwell",
      "Forster",
      "Penrith",
      "Goonellabah",
      "Leopold",
      "Campbelltown",
      "Rutherford",
      "Nambour",
      "Corinda",
      "Muswellbrook",
      "Kingston",
      "Grafton",
      "Bowral",
      "Kingaroy",
      "Casino",
      "Swan Hill",
      "Parkes",
      "Mudgee",
      "Mount Evelyn",
      "Inverell",
      "Andergrove",
      "Nowra",
      "Flemington",
      "Colac",
      "Bargara",
      "Ballina",
      "Mareeba",
      "Moss Vale",
      "Springwood",
      "Rye",
      "Cowra",
      "Beenleigh",
      "Tweed Heads",
      "Emu Plains",
      "Charters Towers",
      "Katoomba",
      "Mooroopna",
      "Maryborough",
      "Young",
      "Narre Warren North",
      "Clifton Springs",
      "Castlemaine",
      "Kingscliff",
      "Fremantle",
      "Leeton",
      "Blaxland",
      "Kyabram",
      "Sanctuary Point",
      "Moama",
      "Merrimac",
      "Moree",
      "Murwillumbah",
      "Urraween",
      "Bongaree",
      "Bomaderry",
      "Ulverstone",
      "Dromana",
      "Helensburgh",
      "Seymour",
      "Port Augusta",
      "Burpengary",
      "Waterford",
      "Deniliquin",
      "Strathalbyn",
      "Lennox Head",
      "Nambucca Heads",
      "Wauchope",
      "Tumut",
      "Nuriootpa",
      "Tuncurry",
      "Yamba",
      "Lakes Entrance",
      "Kurri Kurri",
      "North Mackay",
      "Yass",
      "Mittagong",
      "Cootamundra",
      "Cannonvale",
      "Point Vernon",
      "Palmwoods",
      "Leongatha",
      "Stawell",
      "Narrabri",
      "Whittlesea",
      "Corowa",
      "Inverloch",
      "New Norfolk",
      "Richmond",
      "Wynyard",
      "Woolgoolga",
      "Glen Innes",
      "Alstonville",
      "Worragee",
      "Glenbrook",
      "Nairne",
      "Tahmoor",
      "Scone",
      "Kiama Downs",
      "Hazelbrook",
      "Lithgow",
      "Encounter Bay",
      "Boulder",
      "Salamander Bay",
      "Albury",
      "Bucasia",
      "Millicent",
      "Churchill",
      "Renmark",
      "Wingham",
      "Maffra",
      "Glenella",
      "Rasmussen",
      "Tanunda",
      "Old Bar",
      "George Town",
      "Wyong",
      "Broadford",
      "Drysdale",
      "Tatura",
      "Cockatoo",
      "Deeragun",
      "Victor Harbor",
      "Latrobe",
      "Berri",
      "Wellington",
      "Thirlmere",
      "Legana",
      "Temora",
      "The Entrance",
      "Mansfield",
      "Gerringong",
      "Loxton",
      "Somerset",
      "Korumburra",
      "Picton",
      "Trafalgar",
      "Pearcedale",
      "Numurkah",
      "Peregian Beach",
      "Narrandera",
      "Suffolk Park",
      "Buninyong",
      "Longford",
      "Kerang",
      "Weston",
      "Sawtell",
      "Silverdale",
      "Roxby Downs",
      "Bay View",
      "Lismore",
      "Merimbula",
      "Scarness",
      "Lake Cathie",
      "Paynesville",
      "Maddingley",
      "Proserpine",
      "Cobar",
      "Aldgate",
      "Port Fairy",
      "Koo-Wee-Rup",
      "Penguin",
      "Beachmere",
      "Smithton",
      "McLaren Vale",
      "Euroa",
      "Bellingen",
      "Mullumbimby",
      "Tura Beach",
      "Eden",
      "Red Cliffs",
      "Bogangar",
      "Shoalhaven Heads",
      "Blayney",
      "Stirling",
      "Wilton",
      "Kapunda",
      "Terranora",
      "Woori Yallock",
      "Saint Georges Basin",
      "Camperdown",
      "Culburra",
      "Deloraine",
      "Tea Gardens",
      "Bonny Hills",
      "McCrae",
      "North Wonthaggi",
      "Thursday Island",
      "Urunga",
      "Vincentia",
      "West Wyalong",
      "Howlong",
      "Lawson",
      "Narooma",
      "Quirindi",
      "Condobolin",
      "Margate",
      "Aberdare",
      "Dodges Ferry",
      "Gilgandra",
      "Launching Place",
      "Goolwa",
      "Rutherglen",
      "Hahndorf",
      "Willunga",
      "Sandy Beach",
      "Hadspen",
      "Beaconsfield Upper",
      "Hill Top",
      "Williamstown",
      "Jindabyne",
      "Freeling",
      "Lobethal",
      "The Oaks",
      "Baxter",
      "Saint Arnaud",
      "Esperance",
      "Heddon Greta",
      "Freshwater",
      "Grenfell",
      "Bangalow",
      "Kawana Waters",
      "Orbost",
      "Manilla",
      "Camden Haven",
      "Wallerawang",
      "Wattleglen",
      "Mulwala",
      "Barmera",
      "Windsor",
      "Woodside",
      "Lyndoch",
      "Batehaven",
      "Queenstown",
      "Yarram",
      "Brunswick Heads",
      "Waikerie",
      "Westbury",
      "Yaroomba",
      "Curlewis",
      "Denman",
      "Bourke",
      "Nathalia",
      "Tathra",
      "Cobden",
      "Drummond Cove",
      "Canowindra",
      "Yarragon",
      "Walgett",
      "Surfside",
      "Seven Mile Beach",
      "San Remo",
      "Greenwell Point",
      "Valley Heights",
      "Oakdale",
      "Yallourn North",
      "Innisfail",
      "Mollymook",
      "Evandale",
      "Wahgunyah",
    ],
  },
  {
    name: "Austria",
    cities: [
      "Vienna",
      "Graz",
      "Linz",
      "Lochau",
      "Salzburg",
      "Innsbruck",
      "Klagenfurt",
      "Villach",
      "Wels",
      "Sankt Pölten",
      "Krems an der Donau",
      "Dornbirn",
      "Wiener Neustadt",
      "Steyr",
      "Bregenz",
      "Leonding",
      "Klosterneuburg",
      "Baden",
      "Traun",
      "Lustenau",
      "Amstetten",
      "Kapfenberg",
      "Hallein",
      "Mödling",
      "Kufstein",
      "Traiskirchen",
      "Schwechat",
      "Hohenems",
      "Stockerau",
      "Ansfelden",
      "Telfs",
      "Bruck an der Mur",
      "Spittal an der Drau",
      "Perchtoldsdorf",
      "Bludenz",
      "Eisenstadt",
      "Hall in Tirol",
      "Wörgl",
      "Schwaz",
      "Marchtrenk",
      "Hard",
      "Leibnitz",
      "Korneuburg",
      "Neunkirchen",
      "Knittelfeld",
      "Vöcklabruck",
      "Enns",
      "Lienz",
      "Brunn am Gebirge",
      "Rankweil",
      "Bad Vöslau",
      "Weiz",
      "Götzis",
      "Gänserndorf",
      "Gerasdorf bei Wien",
      "Gleisdorf",
      "Lauterach",
      "Strasshof an der Nordbahn",
      "Köflach",
      "Laakirchen",
      "Purkersdorf",
      "Wiener Neudorf",
      "Voitsberg",
      "Rum",
      "Guntramsdorf",
      "Attnang-Puchheim",
      "Maria Enzersdorf",
      "Deutsch-Wagram",
      "Wolfurt",
      "Perg",
      "Langenzersdorf",
      "Höchst",
      "Freistadt",
      "Bruck an der Leitha",
      "Landeck",
      "Pasching",
      "Kottingbrunn",
      "Seiersberg",
      "Grödig",
      "Zeltweg",
      "Hafendorf",
      "Jenbach",
      "Vösendorf",
      "Kalsdorf bei Graz",
      "Völs",
      "Hartberg",
      "Altach",
      "Feldkirchen bei Graz",
      "Asten",
      "Mattighofen",
      "Gallneukirchen",
      "Hörbranz",
      "Neuhofen an der Krems",
      "Hörsching",
      "Gloggnitz",
      "Wagna",
      "Kirchbichl",
      "Oberndorf bei Salzburg",
      "Timelkam",
      "Thalheim bei Wels",
      "Bergheim",
      "Wildon",
      "Schwertberg",
      "Bad Gleichenberg",
      "Schärding",
      "Lieboch",
      "Leopoldsdorf",
      "Stadl-Paura",
      "Lenzing",
      "Bad Hall",
      "Sollenau",
      "Grieskirchen",
      "Birkfeld",
      "Mauthausen",
      "Leobersdorf",
      "Bürmoos",
      "Weißkirchen in Steiermark",
      "Althofen",
      "Bisamberg",
      "Ottensheim",
      "Oberwaltersdorf",
      "Eichgraben",
      "Koblach",
      "Neudörfl",
      "Mils bei Solbad Hall",
      "Kirchdorf",
      "Puchenau",
      "Wies",
      "Sankt Georgen im Attergau",
      "Oberalm",
      "Tribuswinkel",
      "Felixdorf",
      "Schwanenstadt",
      "Fügen",
      "Anif",
      "Hallwang",
      "Bad Schallerbach",
      "Götzens",
      "Sankt Georgen an der Gusen",
      "Eferding",
      "Mäder",
      "Gössendorf",
      "Schwarzach",
      "Gumpoldskirchen",
      "Fußach",
      "Pinsdorf",
      "Loosdorf",
      "Gratwein",
      "Pfaffstätten",
      "Schwarzach im Pongau",
      "Theresienfeld",
      "Ludesch",
      "Lambach",
      "Neufeld an der Leitha",
      "Göfis",
      "Fernitz",
      "Hausmannstätten",
      "Pirka",
      "Kierling",
      "Sankt Florian am Inn",
      "Klaus",
      "Brixlegg",
      "Ennsdorf",
      "Kematen in Tirol",
      "Biedermannsdorf",
      "Elixhausen",
      "Niederndorf",
      "Gallspach",
      "Aldrans",
      "Sankt Marein im Mürztal",
      "Kaindorf an der Sulm",
      "Rohrbach",
      "Sulz",
      "Raaba",
      "Schlins",
      "Windischgarsten",
      "Bludesch",
      "Werndorf",
      "Gießhübl",
      "Meiningen",
      "Sistrans",
      "Thüringen",
      "Aschach an der Donau",
    ],
  },
  {
    name: "Azerbaijan",
    cities: [
      "Baku",
      "Sumqayıt",
      "Gəncə",
      "Ağcabədi",
      "Mingəçevir",
      "Xırdalan",
      "Naxçıvan",
      "Şatrovka",
      "Qaraçuxur",
      "Hövsan",
      "Bakıxanov",
      "Şirvan",
      "Şəki",
      "Yevlax",
      "M.Ə. Rəsulzadə",
      "Lənkəran",
      "Xankəndi",
      "Biləcəri",
      "Maştağa",
      "Şəmkir",
      "Xaçmaz",
      "Şamaxı",
      "Bərdə",
      "Quba",
      "Göygöl",
      "Binəqədi",
      "Göyçay",
      "Lökbatan",
      "Qazax",
      "Buzovna",
      "İmişli",
      "Zaqatala",
      "Sabirabad",
      "Salyan",
      "Ağdaş",
      "Əmircan",
      "Hacıqabul",
      "Binə",
      "Cəlilabad",
      "Keşlə",
      "Mərdəkan",
      "Zabrat",
      "Sabunçu",
      "Sahil",
      "Hacı Zeynalabdin",
      "İsmayıllı",
      "Ağsu",
      "Ağstafa",
      "Biləsuvar",
      "Siyəzən",
      "Saatlı",
      "Bülbülə",
      "Hindarx",
      "Astara",
      "Qusar",
      "Yeni Suraxanı",
      "Qazyan",
      "Ərkivan",
      "Kürdəmir",
      "Şüvəlan",
      "Masallı",
      "Qobustan",
      "Ucar",
      "Neftçala",
      "Nehrəm",
      "Pirallahı",
      "Tovuz",
      "Baş Göynük",
      "Quzanlı",
      "Corat",
      "Qazmalar",
      "Ələt",
      "Tərtər",
      "Culfa",
      "Beyləqan",
      "Badamdar",
      "Balaxanı",
      "Liman",
      "Qax",
      "Zirə",
      "Əhmədli",
      "Xudat",
      "Əliabad",
      "Saray",
      "Daşkəsən",
      "Ordubad",
      "Samux",
      "Qovlar",
      "Türkan",
      "Naftalan",
      "Göytəpə",
      "Boladı",
      "Sədərək",
      "Gədəbəy",
      "Zərdab",
      "Nardaran",
      "Bilgəh",
      "Yarlı",
      "Ərçivan",
      "Zəyəm",
      "Qalağayın",
      "Yardımlı",
      "Mahmudavar",
      "Zəyəm Cırdaxan",
      "Düyərli",
      "Goranboy",
      "Lerik",
      "Oğuz",
      "Xaçmaz",
      "Kür",
      "Alar",
      "Xındırıstan",
      "Kürdəxanı",
      "Osakücə",
      "Kiş",
      "Aşağı Seyfəli",
      "Uzuntəpə",
      "Cəbrayıl",
      "Təzə Alvadı",
      "Ceyranbatan",
      "Abulbəyli",
      "Zığ",
      "Bığır",
      "Keçili",
      "Xocavənd",
      "Babək",
      "Boradigah",
      "Gərmətük",
      "Dəliməmmədli",
      "Ləkçılpaq",
      "Şiştəpə",
      "Qaracəmirli",
      "Qızılağac",
      "Xocəsən",
      "Dəllər Cəyir",
      "Nərimanabad",
      "Qaradağlı",
      "Pirşağı",
      "Şiyəkəran",
      "Pensər",
      "Təzəkənd",
      "Girdəni",
      "Lənbəran",
      "Sabirkənd",
      "Ağdərə",
      "Novxanı",
      "Hökməli",
      "Şuşa",
      "Qıvraq",
      "Kijəbə",
      "Mamusta",
      "Vilvan",
      "Zəngişalı",
      "Şahağac",
      "Dəllər",
      "Privolnoye",
      "Dadva",
      "Şağlasər",
      "Hadrut",
      "Ocaqlı",
      "Könüllü",
      "İrmaşlı",
      "Qobustan",
      "Şağlakücə",
      "Qarağac",
      "Xıl",
      "Ağdam",
      "Sütəmurdov",
      "Xırmandalı",
      "Dəllər Cırdaxan",
      "Çinarlı",
      "Digah",
      "İnçə",
      "Sabirabad",
      "Potu",
      "Maşlıq",
      "Kakalos",
      "Köhnə Alvadı",
      "Çərəkə",
      "Viravul",
      "Mərzili",
      "Musakücə",
      "İvanovka",
      "Təngərüd",
      "Masazır",
      "Aşağı Nüvədi",
      "Göyəçöl",
      "Şağan",
      "Separadi",
      "Əlimərdanlı",
      "Muxtariyyat",
      "Caxırlı",
      "Kətəlparaq",
      "Digah",
      "Göyşaban",
      "Müşkür",
      "Kərgəlan",
      "Qaravəlli",
      "Abbaslı",
      "Şıxakəran",
      "Yenikənd",
      "Qala",
      "Məmmədli",
      "Aşağı Güzdək",
      "Qapanlı",
      "Yuxarı Qaramanlı",
      "Qaraçuq",
      "Türkoba",
      "Komanlı",
      "Haftoni",
      "Bayramlı",
      "Sulutəpə",
      "Viyən",
      "Mustafaağalı",
      "Mollalı",
      "Əhmədağalı",
      "Üçoğlan",
      "Əlibəyli",
      "Həsənli",
      "Hişkədərə",
      "Əliqasımlı",
      "Təzəkənd",
      "Maşxan",
      "Tatarlı",
      "Qasım İsmayılov",
      "Amsar",
      "Zövlə",
      "Urva",
      "Qarabaqqal",
      "Balıqçılar",
      "Qaraxanbəyli",
      "Güllütəpə",
      "İsgəndərli",
      "Ağdaş",
      "Qubaxəlilli",
      "Digah",
      "Mırtı",
      "Xolmili",
      "Əfətli",
      "Bəcirəvan",
      "Hacıqəhrəmanlı",
      "Gəndov",
      "Banbaşı",
      "Şiləvar",
      "Şahbuz",
      "Laçın",
      "Heydərabad",
      "Balakən",
      "Xızı",
      "Xocalı",
      "Qubadlı",
      "Kəlbəcər",
      "Füzuli",
      "Şərur",
      "Qəbələ",
      "Dəvəçi",
    ],
  },
  {
    name: "Bahamas",
    cities: [
      "Nassau",
      "Lucaya",
      "Freeport City",
      "West End",
      "Marsh Harbour",
      "Georgetown",
      "Clarence Town",
      "Dunmore Town",
      "Rock Sound",
      "Tarpum Bay",
      "Cooper’s Town",
      "Nicholls Town",
      "Snug Corner",
      "Sweeting Cay",
      "Spring City Settlement",
      "Hope Town",
      "Matthew Town",
      "Andros Town",
      "Wemyss Bight",
      "Alice Town",
      "Cockburn Town",
      "Pirates Well",
      "Winton Meadows",
      "Yamacraw Beach Estate",
      "Tusculum",
      "Carmichael Village",
      "Golden Gates Estates",
      "Waterloo",
      "Winton Heights",
      "Millars",
      "Cable Beach",
      "Cunningham",
      "Coral Harbour",
      "Mount Pleasant",
      "Adelaide",
      "Macbride",
      "Highbury Park",
      "Winton",
      "Millar Heights",
      "Gambier Village",
      "Love",
      "Nassau Estate",
      "Killarney",
      "Sandilands Village",
      "Belair Estates",
      "Stapleton Gardens",
      "Orange Hill",
      "Clifton",
      "Creek Village",
      "Coral Heights",
      "Camperdown",
      "Sea Breeze Estates",
      "Bradford",
      "Nixon’s Harbour",
      "Louis Town",
      "Bailey Town",
      "Bluff",
      "Roberts Town",
      "Bain Town",
      "Water Cay",
      "Thomas Town",
      "Hope Estate",
      "Holmes Rock",
      "Eight Mile Rock",
      "Vincent Town",
      "McLeans Town",
      "Pinders Point",
      "Smith Point",
      "Pine Ridge",
      "Russell Town",
      "Hunters",
      "Martin Town",
      "Southwest Point",
      "Pelican Point",
      "Hawksbill",
      "Mather Town",
      "High Rock",
      "Braudies Point",
      "Sea Grape",
      "Bevans Town",
      "Williams Town",
      "Freetown",
      "Golden Grove",
      "Gilbert Grant",
      "Baraterre",
      "Calvin Hill",
      "Curtis",
      "Pigeon Cay",
      "Michelson",
      "Anne’s Tract Settlement",
      "Hermitage",
      "Farmer’s Hill",
      "Rolletown",
      "Steventon",
      "Hartswell",
      "Little Farmers Cay",
      "Richmond Hill",
      "Forbes Hill",
      "Mount Thompson",
      "Rolleville",
      "Moss Town",
      "Rokers Point Settlement",
      "Jimmy Hill",
      "Stuart Manor",
      "Black Point",
      "Ramsey",
      "Alexander",
      "Forest",
      "The Ferry Settlement",
    ],
  },
  {
    name: "Bahrain",
    cities: [
      "Manama",
      "Al Muḩarraq",
      "Madīnat Ḩamad",
      "Jidd Ḩafş",
      "Madīnat ‘Īsá",
      "Sitrah",
      "Ḩālat an Na‘īm",
      "Kaflān",
      "Karbābād",
      "Jabalat Ḩabashī",
      "‘Ayn ad Dār",
      "Ḩillat ‘Abd aş Şāliḩ",
      "Al Muqshā‘",
      "Manī",
      "Al Muwaylighah",
      "Al Busaytīn",
      "Rayyā",
      "‘Arād",
      "Qalālī",
      "Samāhīj",
      "Ad Dayr",
      "Ḩālat as Sulţah",
      "Az Zimmah",
      "Ḩālat al Khulayfāt",
      "Al Ḩadd",
      "Umm ash Shajar",
      "Al Hujayr",
      "An Nuwaydirāt",
      "Al Jubaylāt",
      "Al Qaryah",
      "Ḩālah",
      "Marqūbān",
      "Sufālah",
      "Ḩālat Umm al Bayḑ",
      "Al ‘Akr",
      "Al Ma‘āmīr",
      "Jidd ‘Alī",
      "Jurdāb",
      "Sanad",
      "Al Khārijīyah",
      "Kawrah",
      "Mahazzah",
      "Wādiyān",
      "Salmābād",
      "Tūblī",
      "Ar Rifā‘",
      "‘Ālī",
      "Al Qadam",
      "Jamālah",
    ],
  },
  {
    name: "Bangladesh",
    cities: [
      "Dhaka",
      "Chattogram",
      "Khulna",
      "Rajshahi",
      "Sylhet",
      "Barisal",
      "Rangpur",
      "Mymensingh",
      "Comilla",
      "Narayanganj",
      "Gazipur",
      "Bogra",
      "Jessore",
      "Dinajpur",
      "Saidpur",
      "Nawabganj",
      "Tangail",
      "Pabna",
      "Feni",
      "Kushtia",
      "Cox's Bazar",
      "Madaripur",
      "Faridpur",
      "Manikganj",
      "Habiganj",
      "Brahmanbaria",
      "Narsingdi",
      "Satkhira",
      "Gopalganj",
      "Jamalpur",
      "Sherpur",
      "Shariatpur",
      "Netrokona",
      "Munshiganj",
      "Narail",
      "Chandpur",
      "Kishoreganj",
      "Sunamganj",
      "Lakshmipur",
      "Jhenaidah",
      "Magura",
      "Chuadanga",
      "Meherpur",
      "Bagerhat",
      "Bhola",
      "Patuakhali",
      "Barguna",
      "Barisal",
      "Pirojpur",
      "Jhalokati",
      "Rajbari",
      "Gaibandha",
      "Lalmonirhat",
      "Nilphamari",
      "Kurigram",
      "Panchagarh",
      "Thakurgaon",
      "Rangamati",
      "Khagrachari",
      "Bandarban",
      "Moulvibazar",
    ],
  },
  {
    name: "Barbados",
    cities: [
      "Bridgetown",
      "Speightstown",
      "Holetown",
      "Oistins",
      "Bathsheba",
      "Saint James",
      "Saint Philip",
      "Saint Michael",
      "Saint George",
      "Saint Peter",
      "Saint Joseph",
      "Saint John",
      "Saint Andrew",
      "Saint Thomas",
      "Saint Lucy",
      "Crane",
      "Silver Sands",
      "Hastings",
      "Black Rock",
      "Worthing",
      "Belleplaine",
    ],
  },
  {
    name: "Belarus",
    cities: [
      "Minsk",
      "Gomel",
      "Mogilev",
      "Vitebsk",
      "Hrodna",
      "Brest",
      "Babruysk",
      "Baranovichi",
      "Barysaw",
      "Pinsk",
      "Orsha",
      "Mazyr",
      "Salihorsk",
      "Lida",
      "Polotsk",
      "Zhlobin",
      "Svetlogorsk",
      "Slutsk",
      "Rechytsa",
      "Novopolotsk",
      "Maladzyechna",
      "Kobryn",
      "Volkovysk",
      "Kalinkavichy",
      "Mozyr",
      "Zaslawye",
      "Asipovichy",
      "Navahrudak",
      "Slonim",
      "Vawkavysk",
      "Bereza",
      "Dzerzhinsk",
      "Nesvizh",
      "Byaroza",
      "Ivanava",
      "Luninyets",
      "Chervyen",
      "Marina Horka",
      "Horki",
      "Shchuchyn",
      "Pruzhany",
      "Krychaw",
      "Fanipol",
      "Stolin",
      "Vilejka",
      "Klimavichy",
      "Masty",
      "Lelchytsy",
      "Chashniki",
      "Shklow",
      "Smalyavichy",
      "Chachersk",
      "Drahichyn",
      "Ashmyany",
      "Voranava",
      "Myory",
      "Pastavy",
      "Karelichy",
      "Nyasvizh",
    ],
  },
  {
    name: "Belgium",
    cities: [
      "Brussels",
      "Antwerp",
      "Ghent",
      "Charleroi",
      "Liège",
      "Bruges",
      "Namur",
      "Leuven",
      "Mons",
      "Aalst",
      "Mechelen",
      "La Louvière",
      "Kortrijk",
      "Hasselt",
      "Ostend",
      "Sint-Niklaas",
      "Tournai",
      "Genk",
      "Seraing",
      "Roeselare",
      "Verviers",
      "Mouscron",
      "Beveren",
      "Dendermonde",
      "Turnhout",
      "Heist-op-den-Berg",
      "Sint-Truiden",
      "Lokeren",
      "Beringen",
      "Dilbeek",
      "Halle",
      "Vilvoorde",
      "Herstal",
      "Châtelet",
      "Braine-l'Alleud",
      "Waregem",
      "Louvain-la-Neuve",
      "Binche",
      "Nivelles",
      "Zottegem",
      "Ath",
      "Tienen",
      "Geel",
      "Ieper",
      "Grimbergen",
      "Herentals",
      "Tongeren",
      "Maaseik",
      "Geraardsbergen",
      "Evergem",
      "Aarschot",
      "Eeklo",
      "Zaventem",
      "Knokke-Heist",
      "Wevelgem",
      "Hamme",
      "Oudenaarde",
      "Chaudfontaine",
      "Schoten",
      "Lier",
      "Lommel",
      "Kapellen",
      "Arlon",
      "Deinze",
      "Maldegem",
      "Mortsel",
      "Sint-Pieters-Leeuw",
      "Ravels",
      "Blankenberge",
      "Zedelgem",
      "Koksijde",
      "Wavre",
      "Houthalen-Helchteren",
      "Brecht",
      "Boom",
      "Edegem",
      "Lebbeke",
      "De Panne",
      "Overijse",
      "Vilvoorde",
      "Meise",
      "Poperinge",
      "Waregem",
      "Zemst",
      "Avelgem",
    ],
  },
  { name: "Belize", cities: ["Belmopan"] },
  { name: "Benin", cities: ["Porto-Novo"] },
  { name: "Bhutan", cities: ["Thimphu"] },
  { name: "Bolivia", cities: ["La Paz"] },
  { name: "Bosnia and Herzegovina", cities: ["Sarajevo"] },
  { name: "Botswana", cities: ["Gaborone"] },
  { name: "Brazil", cities: ["Brasília"] },
  { name: "Brunei", cities: ["Bandar Seri Begawan"] },
  { name: "Bulgaria", cities: ["Sofia"] },
  { name: "Burkina Faso", cities: ["Ouagadougou"] },
  { name: "Burundi", cities: ["Gitega"] },
  { name: "Cabo Verde", cities: ["Praia"] },
  { name: "Cambodia", cities: ["Phnom Penh"] },
  { name: "Cameroon", cities: ["Yaoundé"] },
  { name: "Canada", cities: ["Toronto"] },
  { name: "Central African Republic", cities: ["Bangui"] },
  { name: "Chad", cities: ["N'Djamena"] },
  { name: "Chile", cities: ["Santiago"] },
  { name: "China", cities: ["Beijing"] },
  { name: "Colombia", cities: ["Bogotá"] },
  { name: "Comoros", cities: ["Moroni"] },
  { name: "Congo (Congo-Brazzaville)", cities: ["Brazzaville"] },
  { name: "Costa Rica", cities: ["San José"] },
  { name: "Croatia", cities: ["Zagreb"] },
  { name: "Cuba", cities: ["Havana"] },
  { name: "Cyprus", cities: ["Nicosia"] },
  { name: "Czechia (Czech Republic)", cities: ["Prague"] },
  { name: "Democratic Republic of the Congo", cities: ["Kinshasa"] },
  { name: "Denmark", cities: ["Copenhagen"] },
  { name: "Djibouti", cities: ["Djibouti"] },
  { name: "Dominica", cities: ["Roseau"] },
  { name: "Dominican Republic", cities: ["Santo Domingo"] },
  { name: "Ecuador", cities: ["Quito"] },
  { name: "Egypt", cities: ["Cairo"] },
  { name: "El Salvador", cities: ["San Salvador"] },
  { name: "Equatorial Guinea", cities: ["Malabo"] },
  { name: "Eritrea", cities: ["Asmara"] },
  { name: "Estonia", cities: ["Tallinn"] },
  { name: "Eswatini", cities: ["Mbabane"] },
  { name: "Ethiopia", cities: ["Addis Ababa"] },
  { name: "Fiji", cities: ["Suva"] },
  { name: "Finland", cities: ["Helsinki"] },
  { name: "France", cities: ["Paris"] },
  { name: "Gabon", cities: ["Libreville"] },
  { name: "Gambia", cities: ["Banjul"] },
  { name: "Georgia", cities: ["Tbilisi"] },
  { name: "Germany", cities: ["Berlin"] },
  { name: "Ghana", cities: ["Accra"] },
  { name: "Greece", cities: ["Athens"] },
  { name: "Grenada", cities: ["Saint George's"] },
  { name: "Guatemala", cities: ["Guatemala City"] },
  { name: "Guinea", cities: ["Conakry"] },
  { name: "Guinea-Bissau", cities: ["Bissau"] },
  { name: "Guyana", cities: ["Georgetown"] },
  { name: "Haiti", cities: ["Port-au-Prince"] },
  { name: "Honduras", cities: ["Tegucigalpa"] },
  { name: "Hungary", cities: ["Budapest"] },
  { name: "Iceland", cities: ["Reykjavik"] },
  { name: "India", cities: ["New Delhi"] },
  { name: "Indonesia", cities: ["Jakarta"] },
  { name: "Iran", cities: ["Tehran"] },
  { name: "Iraq", cities: ["Baghdad"] },
  { name: "Ireland", cities: ["Dublin"] },
  { name: "Israel", cities: ["Jerusalem"] },
  { name: "Italy", cities: ["Rome"] },
  { name: "Jamaica", cities: ["Kingston"] },
  { name: "Japan", cities: ["Tokyo"] },
  { name: "Jordan", cities: ["Amman"] },
  { name: "Kazakhstan", cities: ["Nur-Sultan"] },
  { name: "Kenya", cities: ["Nairobi"] },
  { name: "Kiribati", cities: ["Tarawa"] },
  { name: "Kuwait", cities: ["Kuwait City"] },
  { name: "Kyrgyzstan", cities: ["Bishkek"] },
  { name: "Laos", cities: ["Vientiane"] },
  { name: "Latvia", cities: ["Riga"] },
  { name: "Lebanon", cities: ["Beirut"] },
  { name: "Lesotho", cities: ["Maseru"] },
  { name: "Liberia", cities: ["Monrovia"] },
  { name: "Libya", cities: ["Tripoli"] },
  { name: "Liechtenstein", cities: ["Vaduz"] },
  { name: "Lithuania", cities: ["Vilnius"] },
  { name: "Luxembourg", cities: ["Luxembourg City"] },
  { name: "Madagascar", cities: ["Antananarivo"] },
  { name: "Malawi", cities: ["Lilongwe"] },
  { name: "Malaysia", cities: ["Kuala Lumpur"] },
  { name: "Maldives", cities: ["Malé"] },
  { name: "Mali", cities: ["Bamako"] },
  { name: "Malta", cities: ["Valletta"] },
  { name: "Marshall Islands", cities: ["Majuro"] },
  { name: "Mauritania", cities: ["Nouakchott"] },
  { name: "Mauritius", cities: ["Port Louis"] },
  { name: "Mexico", cities: ["Mexico City"] },
  { name: "Micronesia", cities: ["Palikir"] },
  { name: "Moldova", cities: ["Chisinau"] },
  { name: "Monaco", cities: ["Monaco"] },
  { name: "Mongolia", cities: ["Ulaanbaatar"] },
  { name: "Montenegro", cities: ["Podgorica"] },
  { name: "Morocco", cities: ["Rabat"] },
  { name: "Mozambique", cities: ["Maputo"] },
  { name: "Myanmar (formerly Burma)", cities: ["Naypyidaw"] },
  { name: "Namibia", cities: ["Windhoek"] },
  { name: "Nauru", cities: ["Yaren"] },
  { name: "Nepal", cities: ["Kathmandu"] },
  { name: "Netherlands", cities: ["Amsterdam"] },
  { name: "New Zealand", cities: ["Wellington"] },
  { name: "Nicaragua", cities: ["Managua"] },
  { name: "Niger", cities: ["Niamey"] },
  { name: "Nigeria", cities: ["Abuja"] },
  { name: "North Korea", cities: ["Pyongyang"] },
  { name: "North Macedonia", cities: ["Skopje"] },
  { name: "Norway", cities: ["Oslo"] },
  { name: "Oman", cities: ["Muscat"] },
  { name: "Pakistan", cities: ["Islamabad"] },
  { name: "Palau", cities: ["Ngerulmud"] },
  { name: "Panama", cities: ["Panama City"] },
  { name: "Papua New Guinea", cities: ["Port Moresby"] },
  { name: "Paraguay", cities: ["Asunción"] },
  { name: "Peru", cities: ["Lima"] },
  { name: "Philippines", cities: ["Manila"] },
  { name: "Poland", cities: ["Warsaw"] },
  { name: "Portugal", cities: ["Lisbon"] },
  { name: "Qatar", cities: ["Doha"] },
  { name: "Romania", cities: ["Bucharest"] },
  { name: "Russia", cities: ["Moscow"] },
  { name: "Rwanda", cities: ["Kigali"] },
  { name: "Saint Kitts and Nevis", cities: ["Basseterre"] },
  { name: "Saint Lucia", cities: ["Castries"] },
  { name: "Saint Vincent and the Grenadines", cities: ["Kingstown"] },
  { name: "Samoa", cities: ["Apia"] },
  { name: "San Marino", cities: ["San Marino"] },
  { name: "Sao Tome and Principe", cities: ["São Tomé"] },
  { name: "Saudi Arabia", cities: ["Riyadh"] },
  { name: "Senegal", cities: ["Dakar"] },
  { name: "Serbia", cities: ["Belgrade"] },
  { name: "Seychelles", cities: ["Victoria"] },
  { name: "Sierra Leone", cities: ["Freetown"] },
  { name: "Singapore", cities: ["Singapore"] },
  { name: "Slovakia", cities: ["Bratislava"] },
  { name: "Slovenia", cities: ["Ljubljana"] },
  { name: "Solomon Islands", cities: ["Honiara"] },
  { name: "Somalia", cities: ["Mogadishu"] },
  { name: "South Africa", cities: ["Pretoria"] },
  { name: "South Korea", cities: ["Seoul"] },
  { name: "South Sudan", cities: ["Juba"] },
  { name: "Spain", cities: ["Madrid"] },
  { name: "Sri Lanka", cities: ["Colombo"] },
  { name: "Sudan", cities: ["Khartoum"] },
  { name: "Suriname", cities: ["Paramaribo"] },
  { name: "Sweden", cities: ["Stockholm"] },
  { name: "Switzerland", cities: ["Bern"] },
  { name: "Syria", cities: ["Damascus"] },
  { name: "Taiwan", cities: ["Taipei"] },
  { name: "Tajikistan", cities: ["Dushanbe"] },
  { name: "Tanzania", cities: ["Dodoma"] },
  { name: "Thailand", cities: ["Bangkok"] },
  { name: "Timor-Leste", cities: ["Dili"] },
  { name: "Togo", cities: ["Lomé"] },
  { name: "Tonga", cities: ["Nuku'alofa"] },
  { name: "Trinidad and Tobago", cities: ["Port of Spain"] },
  { name: "Tunisia", cities: ["Tunis"] },
  { name: "Turkey", cities: ["Ankara"] },
  { name: "Turkmenistan", cities: ["Ashgabat"] },
  { name: "Tuvalu", cities: ["Funafuti"] },
  { name: "Uganda", cities: ["Kampala"] },
  { name: "Ukraine", cities: ["Kyiv"] },
  { name: "United Arab Emirates", cities: ["Abu Dhabi"] },
  { name: "United Kingdom", cities: ["London"] },
  { name: "United States", cities: ["New York"] },
  { name: "Uruguay", cities: ["Montevideo"] },
  { name: "Uzbekistan", cities: ["Tashkent"] },
  { name: "Vanuatu", cities: ["Port Vila"] },
  { name: "Vatican City", cities: ["Vatican City"] },
  { name: "Venezuela", cities: ["Caracas"] },
  { name: "Vietnam", cities: ["Hanoi"] },
  { name: "Yemen", cities: ["Sana'a"] },
  { name: "Zambia", cities: ["Lusaka"] },
  { name: "Zimbabwe", cities: ["Harare"] },
];
